// Package envfiles generates .env files from Kubernetes ConfigMaps and Secrets.
// These files are written to a .kdc/envs/ directory alongside the compose output,
// so multiple services can reference the same file via env_file: and variables
// within a file can safely reference each other.
package envfiles

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/morapet/kdc/internal/registry"
)

// Write generates one .env file per ConfigMap and Secret into outputDir.
// Each file is named <resource-name>.env and contains KEY=value lines.
// The outputDir (e.g. ".kdc/envs") is created if it does not exist.
func Write(reg *registry.ResourceRegistry, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("create env output dir %q: %w", outputDir, err)
	}

	for _, cm := range reg.ConfigMaps {
		data := make(map[string]string, len(cm.Data))
		for k, v := range cm.Data {
			data[k] = v
		}
		if err := writeEnvFile(filepath.Join(outputDir, cm.Name+".env"), data, "ConfigMap", cm.Name); err != nil {
			return err
		}
	}

	for _, sec := range reg.Secrets {
		data := make(map[string]string, len(sec.Data)+len(sec.StringData))
		for k, v := range sec.Data {
			data[k] = string(v) // already base64-decoded by K8s JSON unmarshaller
		}
		for k, v := range sec.StringData {
			data[k] = v // StringData takes precedence
		}
		if err := writeEnvFile(filepath.Join(outputDir, sec.Name+".env"), data, "Secret", sec.Name); err != nil {
			return err
		}
	}

	return nil
}

// writeEnvFile writes key=value pairs to path, sorted for deterministic output.
func writeEnvFile(path string, data map[string]string, sourceKind, sourceName string) error {
	keys := make([]string, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Generated by kdc from %s/%s\n", sourceKind, sourceName))
	sb.WriteString("# Edit this file to override values for local development.\n")
	for _, k := range keys {
		sb.WriteString(fmt.Sprintf("%s=%s\n", k, quoteEnvValue(data[k])))
	}

	if err := os.WriteFile(path, []byte(sb.String()), 0o600); err != nil {
		return fmt.Errorf("write env file %q: %w", path, err)
	}
	return nil
}

// quoteEnvValue wraps a value in double quotes if it contains spaces, #, or =,
// escaping any existing double quotes within.
func quoteEnvValue(v string) string {
	if strings.ContainsAny(v, " \t\n#\"'\\$") {
		v = strings.ReplaceAll(v, `\`, `\\`)
		v = strings.ReplaceAll(v, `"`, `\"`)
		return `"` + v + `"`
	}
	return v
}
